// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheCraftShop.Models;

namespace TheCraftShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201215142945_femtitolv")]
    partial class femtitolv
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("TheCraftShop1._0.Models.CraftMethod", b =>
                {
                    b.Property<int>("CraftMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CraftMethodName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CraftMethodId");

                    b.ToTable("CraftMethods");
                });

            modelBuilder.Entity("TheCraftShop1._0.Models.Handicraft", b =>
                {
                    b.Property<int>("HandicraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CraftMethodId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("HandicraftId");

                    b.HasIndex("CraftMethodId");

                    b.ToTable("Handicrafts");
                });

            modelBuilder.Entity("TheCraftShop1._0.Models.Handicraft", b =>
                {
                    b.HasOne("TheCraftShop1._0.Models.CraftMethod", "CraftMethod")
                        .WithMany("Handicrafts")
                        .HasForeignKey("CraftMethodId");

                    b.Navigation("CraftMethod");
                });

            modelBuilder.Entity("TheCraftShop1._0.Models.CraftMethod", b =>
                {
                    b.Navigation("Handicrafts");
                });
#pragma warning restore 612, 618
        }
    }
}
