// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheCraftShop.Models;

namespace TheCraftShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201215170220_seededData")]
    partial class seededData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("TheCraftShop1._0.Models.CraftMethod", b =>
                {
                    b.Property<int>("CraftMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CraftMethodName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CraftMethodId");

                    b.ToTable("CraftMethods");

                    b.HasData(
                        new
                        {
                            CraftMethodId = 1,
                            CraftMethodName = "Virkning"
                        },
                        new
                        {
                            CraftMethodId = 2,
                            CraftMethodName = "Macrame"
                        });
                });

            modelBuilder.Entity("TheCraftShop1._0.Models.Handicraft", b =>
                {
                    b.Property<int>("HandicraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CraftMethodId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("HandicraftId");

                    b.HasIndex("CraftMethodId");

                    b.ToTable("Handicrafts");

                    b.HasData(
                        new
                        {
                            HandicraftId = 1,
                            CraftMethodId = 1,
                            Description = "Virkat set med 5 st fåglar och 4 st grisar, inspirerade av mobilspelet Angry birds.",
                            Image = "Angry_birds.jpg",
                            Name = "Angry-birds set",
                            Price = 500
                        },
                        new
                        {
                            HandicraftId = 2,
                            CraftMethodId = 1,
                            Description = "Virkat set med 2 st \"Fluffies\", inspirerade av mobilspelet Fluffy fall.",
                            Image = "FluffyDuo.jpg",
                            Name = "Fluffy Duo",
                            Price = 200
                        },
                        new
                        {
                            HandicraftId = 3,
                            CraftMethodId = 1,
                            Description = "Virkat set med 2 st figurer, pokemonsen Jigglypuff & Igglybuff.",
                            Image = "JigglyDuo.jpg",
                            Name = "Pokémon Duett",
                            Price = 100
                        },
                        new
                        {
                            HandicraftId = 4,
                            CraftMethodId = 1,
                            Description = "Virkad kattleksak, en mörkröd mus.",
                            Image = "Kattleksak_mus1.jpg",
                            Name = "Kattleksak",
                            Price = 75
                        },
                        new
                        {
                            HandicraftId = 5,
                            CraftMethodId = 1,
                            Description = "Virkat set med 3 st Pokéball. Vanlig, greateball och ultraball",
                            Image = "Pokeballs.jpg",
                            Name = "Pokéballs",
                            Price = 100
                        },
                        new
                        {
                            HandicraftId = 6,
                            CraftMethodId = 1,
                            Description = "Virkat set med en Pokémon i Pokéball, Pikachu.",
                            Image = "Pika_boll.jpg",
                            Name = "Pika-ball",
                            Price = 150
                        },
                        new
                        {
                            HandicraftId = 7,
                            CraftMethodId = 1,
                            Description = "Virkad brosch, vit anemon.",
                            Image = "Brosch_blomma2.jpg",
                            Name = "Brosch 1",
                            Price = 50
                        },
                        new
                        {
                            HandicraftId = 8,
                            CraftMethodId = 1,
                            Description = "Virkad brosch, röd ros.",
                            Image = "Brosch_blomma3.jpg",
                            Name = "Brosch 2",
                            Price = 50
                        },
                        new
                        {
                            HandicraftId = 9,
                            CraftMethodId = 1,
                            Description = "Virkad brosch, studentmössa.",
                            Image = "Brosch_studentmössa.jpg",
                            Name = "Brosch 3",
                            Price = 50
                        },
                        new
                        {
                            HandicraftId = 10,
                            CraftMethodId = 2,
                            Description = "Macrame nyckelring, gran.",
                            Image = "Nyckelring_gran.jpg",
                            Name = "Nyckelring",
                            Price = 50
                        },
                        new
                        {
                            HandicraftId = 11,
                            CraftMethodId = 2,
                            Description = "Macrame gran med silver pärlor att hänga i halsbandet.",
                            Image = "Halsbandshänge_Gran.jpg",
                            Name = "Hänge",
                            Price = 50
                        },
                        new
                        {
                            HandicraftId = 12,
                            CraftMethodId = 2,
                            Description = "Macrame armband.",
                            Image = "Armband.jpg",
                            Name = "Armband",
                            Price = 75
                        },
                        new
                        {
                            HandicraftId = 13,
                            CraftMethodId = 2,
                            Description = "Macrame öronhänge, gröna granar.",
                            Image = "Öronhänge_granar.jpg",
                            Name = "Öronhängen",
                            Price = 75
                        });
                });

            modelBuilder.Entity("TheCraftShop1._0.Models.Handicraft", b =>
                {
                    b.HasOne("TheCraftShop1._0.Models.CraftMethod", "CraftMethod")
                        .WithMany("Handicrafts")
                        .HasForeignKey("CraftMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CraftMethod");
                });

            modelBuilder.Entity("TheCraftShop1._0.Models.CraftMethod", b =>
                {
                    b.Navigation("Handicrafts");
                });
#pragma warning restore 612, 618
        }
    }
}
