// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheCraftShop.Models;

namespace TheCraftShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201217152433_Final-migration")]
    partial class Finalmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("TheCraftShop.Models.CraftMethod", b =>
                {
                    b.Property<int>("CraftMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CraftMethodName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CraftMethodId");

                    b.ToTable("CraftMethods");

                    b.HasData(
                        new
                        {
                            CraftMethodId = 1,
                            CraftMethodName = "Virkning"
                        },
                        new
                        {
                            CraftMethodId = 2,
                            CraftMethodName = "Macrame"
                        },
                        new
                        {
                            CraftMethodId = 3,
                            CraftMethodName = "Tecknat"
                        });
                });

            modelBuilder.Entity("TheCraftShop.Models.Handicraft", b =>
                {
                    b.Property<int>("HandicraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CraftMethodId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsNewItem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("HandicraftId");

                    b.HasIndex("CraftMethodId");

                    b.ToTable("Handicrafts");

                    b.HasData(
                        new
                        {
                            HandicraftId = 1,
                            CraftMethodId = 1,
                            Description = "Virkat set med 5 st fåglar och 4 st grisar, inspirerade av mobilspelet Angry birds.",
                            Image = "AngryBirds.jpg",
                            IsNewItem = false,
                            Name = "AngryBirds set",
                            Price = 500
                        },
                        new
                        {
                            HandicraftId = 2,
                            CraftMethodId = 1,
                            Description = "Virkat set med 2 st \"Fluffies\", inspirerade av mobilspelet Fluffy fall.",
                            Image = "FluffyDuo.jpg",
                            IsNewItem = false,
                            Name = "Fluffy Duo",
                            Price = 200
                        },
                        new
                        {
                            HandicraftId = 3,
                            CraftMethodId = 1,
                            Description = "Virkat set med 2 st figurer, pokemonsen Jigglypuff & Igglybuff.",
                            Image = "JigglyDuo.jpg",
                            IsNewItem = false,
                            Name = "Pokémon Duett",
                            Price = 100
                        },
                        new
                        {
                            HandicraftId = 4,
                            CraftMethodId = 1,
                            Description = "Virkad kattleksak, en mörkröd mus.",
                            Image = "Mus.jpg",
                            IsNewItem = false,
                            Name = "Kattleksak",
                            Price = 75
                        },
                        new
                        {
                            HandicraftId = 5,
                            CraftMethodId = 1,
                            Description = "Virkat set med 3 st Pokéball. Vanlig, greateball och ultraball",
                            Image = "Pokeballs.jpg",
                            IsNewItem = false,
                            Name = "Pokéballs",
                            Price = 100
                        },
                        new
                        {
                            HandicraftId = 6,
                            CraftMethodId = 1,
                            Description = "Virkat set med en Pokémon i Pokéball, Pikachu.",
                            Image = "Pika_boll.jpg",
                            IsNewItem = false,
                            Name = "Pika-ball",
                            Price = 150
                        },
                        new
                        {
                            HandicraftId = 7,
                            CraftMethodId = 1,
                            Description = "Virkad brosch, vit anemon.",
                            Image = "Blomma1.jpg",
                            IsNewItem = false,
                            Name = "Brosch 1",
                            Price = 50
                        },
                        new
                        {
                            HandicraftId = 8,
                            CraftMethodId = 1,
                            Description = "Virkad brosch, röd ros.",
                            Image = "Blomma2.jpg",
                            IsNewItem = true,
                            Name = "Brosch 2",
                            Price = 50
                        },
                        new
                        {
                            HandicraftId = 9,
                            CraftMethodId = 1,
                            Description = "Virkad brosch, studentmössa.",
                            Image = "Studentmössa.jpg",
                            IsNewItem = false,
                            Name = "Brosch 3",
                            Price = 50
                        },
                        new
                        {
                            HandicraftId = 10,
                            CraftMethodId = 2,
                            Description = "Macrame nyckelring, gran.",
                            Image = "Nyckelring.jpg",
                            IsNewItem = false,
                            Name = "Nyckelring",
                            Price = 50
                        },
                        new
                        {
                            HandicraftId = 11,
                            CraftMethodId = 2,
                            Description = "Gran med silver pärlor att hänga i halsbandet.",
                            Image = "Hänge.jpg",
                            IsNewItem = false,
                            Name = "Hänge",
                            Price = 50
                        },
                        new
                        {
                            HandicraftId = 12,
                            CraftMethodId = 2,
                            Description = "Macrame armband.",
                            Image = "Armband.jpg",
                            IsNewItem = false,
                            Name = "Armband",
                            Price = 75
                        },
                        new
                        {
                            HandicraftId = 13,
                            CraftMethodId = 2,
                            Description = "Macrame öronhänge, gröna granar.",
                            Image = "Öronhänge.jpg",
                            IsNewItem = true,
                            Name = "Öronhängen",
                            Price = 75
                        },
                        new
                        {
                            HandicraftId = 14,
                            CraftMethodId = 3,
                            Description = "Målning med akvarell, nedgående sol över havet.",
                            Image = "Solnedgång.jpg",
                            IsNewItem = false,
                            Name = "Solnedgång",
                            Price = 75
                        },
                        new
                        {
                            HandicraftId = 15,
                            CraftMethodId = 3,
                            Description = "Akryl målning, vågor som slår mot en sandstrand.",
                            Image = "Strand.jpg",
                            IsNewItem = false,
                            Name = "Stranden",
                            Price = 75
                        },
                        new
                        {
                            HandicraftId = 16,
                            CraftMethodId = 3,
                            Description = "Blyertsteckning, färglagd med akvarell.",
                            Image = "Träd.jpg",
                            IsNewItem = true,
                            Name = "Träd",
                            Price = 75
                        },
                        new
                        {
                            HandicraftId = 17,
                            CraftMethodId = 3,
                            Description = "Teckning i tusch, hur det känns att ha adhd.",
                            Image = "Hjärna.jpg",
                            IsNewItem = false,
                            Name = "ADHD-Hjärna",
                            Price = 50
                        });
                });

            modelBuilder.Entity("TheCraftShop.Models.Handicraft", b =>
                {
                    b.HasOne("TheCraftShop.Models.CraftMethod", "CraftMethod")
                        .WithMany("Handicrafts")
                        .HasForeignKey("CraftMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CraftMethod");
                });

            modelBuilder.Entity("TheCraftShop.Models.CraftMethod", b =>
                {
                    b.Navigation("Handicrafts");
                });
#pragma warning restore 612, 618
        }
    }
}
